/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sig.views;

import com.sig.controller.InvoiceListener;
import com.sig.models.InvoiceHeader;
import com.sig.models.InvoiceHeaderTableModel;
import com.sig.models.InvoiceLine;
import com.sig.models.InvoiceLinesTableModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author HP
 */
public class InvoiceForm extends javax.swing.JFrame implements ListSelectionListener{

    /**
     * Creates new form InvoiceForm
     */
    public InvoiceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoices = new javax.swing.JTable();
        invoices.getSelectionModel().addListSelectionListener(this);
        createInvoiceButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceDetails = new javax.swing.JTable();
        invoiceNumLable = new javax.swing.JLabel();
        invoiceDateLable = new javax.swing.JLabel();
        customerNameLable = new javax.swing.JLabel();
        invTotallable = new javax.swing.JLabel();
        invouceNolable = new javax.swing.JLabel();
        invoicedatelbl = new javax.swing.JLabel();
        customernamelabel = new javax.swing.JLabel();
        invoiceTotallable = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteInvoiceButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadFileBtn = new javax.swing.JMenuItem();
        SaveFileBtn = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(invoices);

        createInvoiceButton.setText("Create New Invoice");
        createInvoiceButton.addActionListener(actionListener);

        invoiceDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(invoiceDetails);

        invoiceNumLable.setText("Invoice Number");

        invoiceDateLable.setText("Invoice Date");

        customerNameLable.setText("Customer Name");

        invTotallable.setText("Invoice Total");

        saveButton.setText("Save");
        saveButton.addActionListener(actionListener);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(actionListener);

        deleteInvoiceButton.setText("Delete Invoice");
        deleteInvoiceButton.addActionListener(actionListener);

        jMenu1.setText("File");

        LoadFileBtn.setText("Load File");
        LoadFileBtn.addActionListener(actionListener);
        jMenu1.add(LoadFileBtn);

        SaveFileBtn.setText("Save File");
        SaveFileBtn.addActionListener(actionListener);
        jMenu1.add(SaveFileBtn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(customerNameLable)
                                .addComponent(invTotallable, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(invoiceDateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceNumLable))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(invouceNolable)
                            .addComponent(invoicedatelbl)
                            .addComponent(customernamelabel)
                            .addComponent(invoiceTotallable)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(createInvoiceButton)
                .addGap(40, 40, 40)
                .addComponent(deleteInvoiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(115, 115, 115)
                .addComponent(cancelButton)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceNumLable)
                            .addComponent(invouceNolable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceDateLable)
                            .addComponent(invoicedatelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerNameLable)
                            .addComponent(customernamelabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invTotallable)
                            .addComponent(invoiceTotallable))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteInvoiceButton)
                    .addComponent(createInvoiceButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LoadFileBtn;
    private javax.swing.JMenuItem SaveFileBtn;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createInvoiceButton;
    private javax.swing.JLabel customerNameLable;
    private javax.swing.JLabel customernamelabel;
    private javax.swing.JButton deleteInvoiceButton;
    private javax.swing.JLabel invTotallable;
    private javax.swing.JLabel invoiceDateLable;
    private javax.swing.JTable invoiceDetails;
    private javax.swing.JLabel invoiceNumLable;
    private javax.swing.JLabel invoiceTotallable;
    private javax.swing.JLabel invoicedatelbl;
    private javax.swing.JTable invoices;
    private javax.swing.JLabel invouceNolable;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
    private InvoiceListener actionListener=new InvoiceListener(this);
    private ArrayList<InvoiceHeader> invoicesArray;
    private ArrayList<InvoiceLine> invoiceLinesArray;
    private InvoiceHeaderTableModel headerTableModel;
    private InvoiceLinesTableModel linesTableModel;
   
    public static SimpleDateFormat date=new SimpleDateFormat("dd-MM-yyyy");

    public InvoiceLinesTableModel getLinesTableModel() {
        return linesTableModel;
    }

    public void setLinesTableModel(InvoiceLinesTableModel linesTableModel) {
        this.linesTableModel = linesTableModel;
    }
    
    
    public void setInvoicesArray(ArrayList<InvoiceHeader> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }
    
    public InvoiceHeader getInvCode(int code){
    
        for(InvoiceHeader inv:invoicesArray){
            if(inv.getInvoiceNum()==code){
            
                return inv;
            }
        }
        return null;
    }  

    public InvoiceHeaderTableModel getHeaderTableModel() {
        return headerTableModel;
    }
    
    public void setHeaderTableModel(InvoiceHeaderTableModel headerTableModel) {
        this.headerTableModel = headerTableModel;
    }

    public JTable getInvoiceDetails() {
        return invoiceDetails;
    }

    public JTable getInvoices() {
        return invoices;
    }

    public InvoiceListener getActionListener() {
        return actionListener;
    }

    public ArrayList<InvoiceHeader> getInvoicesArray() {
        return invoicesArray;
    }

    public ArrayList<InvoiceLine> getInvoiceLinesArray() {
        return invoiceLinesArray;
    }

    public void setInvoiceLinesArray(ArrayList<InvoiceLine> invoiceLinesArray) {
        this.invoiceLinesArray = invoiceLinesArray;
    }
    
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
        //System.out.println("selection listener");
        selectRowFromInvoices();
    }

    private void selectRowFromInvoices() {
       
        int selectedRow=invoices.getSelectedRow();
        
        if(selectedRow>=0){
        InvoiceHeader row = headerTableModel.getInvoicesArray().get(selectedRow);
        ArrayList<InvoiceLine> lines=row.getLines();
        setInvoiceLinesArray(lines);
        linesTableModel=new InvoiceLinesTableModel(lines);
        invoiceDetails.setModel(linesTableModel);
        linesTableModel.fireTableDataChanged();
        customernamelabel.setText(row.getCustomerName());
        invouceNolable.setText(""+row.getInvoiceNum());
        invoiceTotallable.setText(""+row.sumTotalOfLines());
        invoicedatelbl.setText(InvoiceForm.date.format(row.getInvoiceDate()));
       
        
        }
        
    }

    public JLabel getCustomernamelabel() {
        return customernamelabel;
    }

    public JLabel getInvoiceTotallable() {
        return invoiceTotallable;
    }

    public JLabel getInvoicedatelbl() {
        return invoicedatelbl;
    }

    public JLabel getInvouceNolable() {
        return invouceNolable;
    }
    
    
    }






